/*
 * deBridge Liquidity Network (DLN) API
 *
 * A turnkey solution for a high-performance cross-chain trading<br><br><a href=\"https://docs.debridge.finance/dln-the-debridge-liquidity-network-protocol/interacting-with-the-api/quick-start-guide\">Quick Start Guide</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestResponse {
    #[serde(rename = "errorCode")]
    pub error_code: i32,
    #[serde(rename = "errorId")]
    pub error_id: String,
    #[serde(rename = "errorMessage")]
    pub error_message: String,
}

impl BadRequestResponse {
    pub fn new(error_code: i32, error_id: String, error_message: String) -> BadRequestResponse {
        BadRequestResponse {
            error_code,
            error_id,
            error_message,
        }
    }
}
