/*
 * deBridge Liquidity Network (DLN) API
 *
 * A turnkey solution for a high-performance cross-chain trading<br><br><a href=\"https://docs.debridge.finance/dln-the-debridge-liquidity-network-protocol/interacting-with-the-api/quick-start-guide\">Quick Start Guide</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DlnOrderControllerV10CreateOrder200Response {
    DlnOrderCreateTxResponse(Box<models::DlnOrderCreateTxResponse>),
    DlnOrderQuoteResponse(Box<models::DlnOrderQuoteResponse>),
}

impl Default for DlnOrderControllerV10CreateOrder200Response {
    fn default() -> Self {
        Self::DlnOrderCreateTxResponse(Default::default())
    }
}
