/*
 * deBridge Liquidity Network (DLN) API
 *
 * A turnkey solution for a high-performance cross-chain trading<br><br><a href=\"https://docs.debridge.finance/dln-the-debridge-liquidity-network-protocol/interacting-with-the-api/quick-start-guide\">Quick Start Guide</a>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DstChainTokenOutResponseType {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimals")]
    pub decimals: i32,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "recommendedAmount")]
    pub recommended_amount: String,
    #[serde(rename = "withoutAdditionalTakerRewardsAmount", skip_serializing_if = "Option::is_none")]
    pub without_additional_taker_rewards_amount: Option<String>,
    #[serde(rename = "maxTheoreticalAmount")]
    pub max_theoretical_amount: String,
    #[serde(rename = "approximateUsdValue", skip_serializing_if = "Option::is_none")]
    pub approximate_usd_value: Option<f64>,
    #[serde(rename = "recommendedApproximateUsdValue", skip_serializing_if = "Option::is_none")]
    pub recommended_approximate_usd_value: Option<f64>,
    #[serde(rename = "maxTheoreticalApproximateUsdValue", skip_serializing_if = "Option::is_none")]
    pub max_theoretical_approximate_usd_value: Option<f64>,
    #[serde(rename = "withoutAdditionalTakerRewardsApproximateUsdValue", skip_serializing_if = "Option::is_none")]
    pub without_additional_taker_rewards_approximate_usd_value: Option<f64>,
}

impl DstChainTokenOutResponseType {
    pub fn new(address: String, name: String, symbol: String, decimals: i32, amount: String, chain_id: f64, recommended_amount: String, max_theoretical_amount: String) -> DstChainTokenOutResponseType {
        DstChainTokenOutResponseType {
            address,
            name,
            symbol,
            decimals,
            amount,
            chain_id,
            recommended_amount,
            without_additional_taker_rewards_amount: None,
            max_theoretical_amount,
            approximate_usd_value: None,
            recommended_approximate_usd_value: None,
            max_theoretical_approximate_usd_value: None,
            without_additional_taker_rewards_approximate_usd_value: None,
        }
    }
}

