/*
 * deBridge Liquidity Network (DLN) API
 *
 * A turnkey solution for a high-performance cross-chain trading<br><br><a href=\"https://docs.debridge.finance/dln-the-debridge-liquidity-network-protocol/interacting-with-the-api/quick-start-guide\">Quick Start Guide</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeDetails {
    #[serde(rename = "giveOrderState", skip_serializing_if = "Option::is_none")]
    pub give_order_state: Option<String>,
    #[serde(rename = "giveOrderWallet", skip_serializing_if = "Option::is_none")]
    pub give_order_wallet: Option<String>,
    #[serde(rename = "nonceMaster", skip_serializing_if = "Option::is_none")]
    pub nonce_master: Option<String>,
    #[serde(rename = "txFee", skip_serializing_if = "Option::is_none")]
    pub tx_fee: Option<String>,
    #[serde(rename = "priorityFee", skip_serializing_if = "Option::is_none")]
    pub priority_fee: Option<String>,
    #[serde(rename = "gasLimit", skip_serializing_if = "Option::is_none")]
    pub gas_limit: Option<String>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "baseFee", skip_serializing_if = "Option::is_none")]
    pub base_fee: Option<String>,
    #[serde(rename = "maxFeePerGas", skip_serializing_if = "Option::is_none")]
    pub max_fee_per_gas: Option<String>,
    #[serde(
        rename = "maxPriorityFeePerGas",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_priority_fee_per_gas: Option<String>,
}

impl FeeDetails {
    pub fn new() -> FeeDetails {
        FeeDetails {
            give_order_state: None,
            give_order_wallet: None,
            nonce_master: None,
            tx_fee: None,
            priority_fee: None,
            gas_limit: None,
            gas_price: None,
            base_fee: None,
            max_fee_per_gas: None,
            max_priority_fee_per_gas: None,
        }
    }
}
