/*
 * deBridge Liquidity Network (DLN) API
 *
 * A turnkey solution for a high-performance cross-chain trading<br><br><a href=\"https://docs.debridge.finance/dln-the-debridge-liquidity-network-protocol/interacting-with-the-api/quick-start-guide\">Quick Start Guide</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SrcChainTokenInResponseType {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimals")]
    pub decimals: i32,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "approximateOperatingExpense")]
    pub approximate_operating_expense: String,
    #[serde(rename = "mutatedWithOperatingExpense")]
    pub mutated_with_operating_expense: bool,
    #[serde(rename = "approximateUsdValue")]
    pub approximate_usd_value: f64,
    #[serde(rename = "originApproximateUsdValue")]
    pub origin_approximate_usd_value: f64,
}

impl SrcChainTokenInResponseType {
    pub fn new(
        address: String,
        name: String,
        symbol: String,
        decimals: i32,
        amount: String,
        chain_id: f64,
        approximate_operating_expense: String,
        mutated_with_operating_expense: bool,
        approximate_usd_value: f64,
        origin_approximate_usd_value: f64,
    ) -> SrcChainTokenInResponseType {
        SrcChainTokenInResponseType {
            address,
            name,
            symbol,
            decimals,
            amount,
            chain_id,
            approximate_operating_expense,
            mutated_with_operating_expense,
            approximate_usd_value,
            origin_approximate_usd_value,
        }
    }
}
